# ======================================
# Dify 插件主配置
# ======================================
[Dify]
# 基本设置
enable = true                   # 是否启用插件
default-model = "Gordon"           # 默认使用的模型
commands = ["聊天", "AI", "重置对话"]  # 触发命令列表

# 功能设置
support_agent_mode = true       # 是否支持Agent模式:
                                # true - 支持Agent模式，可以处理agent_thought、agent_message等事件
                                # false - 仅支持基础聊天模式

# 黑名单设置
blacklist_enable = true         # 是否启用黑名单功能
blacklist_users = [             # 黑名单用户列表（微信ID）
    "wxid_filwu8",              # 屏蔽用户 filwu8 (wxid_格式)
    "filwu8",                   # 屏蔽用户 filwu8 (直接格式)
    # "wxid_example2",          # 可以添加多个用户ID
]
blacklist_groups = [            # 黑名单群组列表（群组ID）
    # "group_example1",         # 示例：添加需要屏蔽的群组ID
    # "group_example2",         # 可以添加多个群组ID
]

# 用户提示信息
command-tip = """-----xxxBot-----
💬AI聊天指令：
1. 切换模型（将会一直保持到下次切换）：
   - @Gordon 切换：切换到Gordon模型
   - @老夏 切换：切换到老夏模型
2. 临时使用其他模型：
   - Gordon 消息内容：临时使用Gordon模型
   - 老夏 消息内容：临时使用老夏模型
3. 重置对话：
   - 重置对话：清除当前对话历史，开始新的对话"""

# 权限与积分设置
admin_ignore = true             # 管理员是否免积分，设为true则管理员不消耗积分使用AI
whitelist_ignore = true         # 白名单用户是否免积分，设为true则白名单用户不消耗积分

# 网络与回复设置
http-proxy = ""                 # HTTP代理配置，格式为"http://代理地址:端口"，不需要则留空
voice_reply_all = false         # 是否总是使用语音回复，设为true则所有回复都转为语音消息

# 机器人识别
robot-names = [                 # 用于识别AI名称，在传递到Dify时进行删除
    "智能助手",
    "小小x"
]

# 注意：音频转文本和文本转音频 URL 将基于各模型的 base-url 自动构建

# ======================================
# 模型配置
# ======================================
[Dify.models]

# Gordon模型配置
[Dify.models."Gordon"]
api-key = "appXXXrUApcMl6jQsWiLXXXtU"  # API密钥
base-url = "https://XXXXX/v1"   # API基础URL
trigger-words = ["@Gordon"]                  # 用于切换模型的触发词
wakeup-words = ["Gordon"]                    # 用于唤醒AI的唤醒词
price = 0                                  # 使用价格（积分）
